server:
  port: 8083
spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: 'finePaidEvent:com.example.fineservice.infrastructure.kafka.event.outgoing.FinePaidEvent'
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.loanservice.infrastructure.kafka.event.outgoing
            type:
              mapping: 'bookItemLostEvent:com.example.fineservice.infrastructure.kafka.event.incoming.BookItemLostEvent,
                        bookItemReturnedEvent:com.example.fineservice.infrastructure.kafka.event.incoming.BookItemReturnedEvent'
jwt:
  expirationTime: 360000000 #100h
  #  expirationTime: 900000 #15 min
  secret: 694d057a02aec7b4de008225532c4aa7eadd6759d5f920749adb20a92dc158c1
  refresh-token:
    expiration: 604800000 #7 days
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true