server:
  port: 8084
spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  kafka:
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: com.example.loanservice.domain.event
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka