server:
  port: 8084
spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: 'bookItemLostEvent:com.example.loanservice.domain.event.outgoing.BookItemLostEvent,
                        bookItemReturnedEvent:com.example.loanservice.domain.event.outgoing.BookItemReturnedEvent,
                        loanCreatedEvent:com.example.loanservice.domain.event.outgoing.LoanCreatedEvent,
                        loanProlongationNotAllowed:com.example.loanservice.domain.event.outgoing.LoanProlongationNotAllowed,
                        loanProlongedEvent:com.example.loanservice.domain.event.outgoing.LoanProlongedEvent'
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.requestservice.domain.event.outgoing
            type:
              mapping: 'reservationCreatedEvent:com.example.loanservice.domain.event.incoming.ReservationCreatedEvent'
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka