server:
  port: 8086
spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true