server:
  port: 8087
spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    properties:
      spring:
        json:
          type:
            mapping: 'requestAvailableToLoanEvent:com.example.requestservice.infrastructure.kafka.event.outgoing.RequestAvailableToLoanEvent,
                      requestCanceledEvent:com.example.requestservice.infrastructure.kafka.event.outgoing.RequestCanceledEvent,
                      requestCreatedEvent:com.example.requestservice.infrastructure.kafka.event.outgoing.RequestCreatedEvent,
                      requestReadyEvent:com.example.requestservice.infrastructure.kafka.event.outgoing.RequestReadyEvent,
                      reservationCreatedEvent:com.example.requestservice.infrastructure.kafka.event.outgoing.ReservationCreatedEvent'
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.example.catalogservice.infrastructure.kafka.event.outgoing, com.example.loanservice.infrastructure.kafka.event.outgoing
            type:
              mapping: 'bookItemDeletedEvent:com.example.requestservice.infrastructure.kafka.event.incoming.BookItemDeletedEvent,
                        bookItemLostEvent:com.example.requestservice.infrastructure.kafka.event.incoming.BookItemLostEvent,
                        bookItemReturnedEvent:com.example.requestservice.infrastructure.kafka.event.incoming.BookItemReturnedEvent,
                        loanCreatedEvent:com.example.requestservice.infrastructure.kafka.event.incoming.LoanCreatedEvent'
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka