package com.example.libraryapp.domain.notification.model;

public enum NotificationType {
    BOOK_BORROWED,
    BOOK_AVAILABLE_TO_BORROW,
    BOOK_LOST,
    BOOK_RENEWED,
    BOOK_RESERVED_FIRST_PERSON,
    BOOK_RESERVED_QUEUE,
    BOOK_RETURNED,
    RENEWAL_IMPOSSIBLE,
    REQUEST_CANCELLED,
    REQUEST_COMPLETED,
    REQUEST_CREATED,
    RESERVATION_CANCEL_BOOK_ITEM_LOST,

    USER_REGISTERED,
}
