spring:
  liquibase:
    change-log: db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: validate
  profiles:
    default: dev
    active: dev
springdoc:
  swagger-ui:
    path: /swagger-ui.html

