export enum BookFormat {
    HARDCOVER = "HARDCOVER",
    PAPERBACK = "PAPERBACK",
    AUDIO_BOOK = "AUDIO_BOOK",
    EBOOK = "EBOOK",
    NEWSPAPER = "NEWSPAPER",
    MAGAZINE = "MAGAZINE",
    JOURNAL = "JOURNAL"
}