server:
  port: 8087
spring:
  application:
    name: payment-service
  liquibase:
    change-log: classpath:db/changelog/master.xml
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka