spring:
  liquibase:
    change-log: classpath:db/changelog/master.xml
  jpa:
    hibernate:
      ddl-auto: update
  profiles:
    default: prod
springdoc:
  swagger-ui:
    path: /swagger-ui.html

jwt:
  expirationTime: 360000000 #100h
#  expirationTime: 900000 #15 min
  secret: 694d057a02aec7b4de008225532c4aa7eadd6759d5f920749adb20a92dc158c1
  refresh-token:
     expiration: 604800000 #7 days

app:
  version: '@project.version@'
