spring:
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
  liquibase:
    contexts: dev
  kafka:
    bootstrap-servers: localhost:9092
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka